const cars = [
    {
        "id": 1,
        "brand": "Toyota",
        "model": "Camry",
        "title": "Ford Explorer: Inspiring New Adventures on Wheels",
        "year": 2022,
        "mileage": 145,
        "maxSpeed": 300,
        "price": 36760,
        "oldPrice": 36880,
        "image": "toyota-camry.jpg",
        "type": "SUV",
        "location": "New York",
        "isNew": true
      },
      {
        "id": 2,
        "brand": "Nissan",
        "model": "Altima",
        "title": "Upgrade Your Drive: Explore the Nissan Altima Experience",
        "year": 2021,
        "mileage": 234,
        "maxSpeed": 240,
        "price": 25000,
        "oldPrice": 25900,
        "image": "nissan-altima.jpg",
        "type": "Sedan",
        "location": "Los Angeles",
        "isNew": false
      },
      {
        "id": 3,
        "brand": "BMW",
        "model": "4 Series",
        "title": "Precision Engineering Meets Style: BMW 3 Series",
        "year": 2017,
        "mileage": 43,
        "maxSpeed": 230,
        "price": 50000,
        "oldPrice": 50700,
        "image": "bmw-4series.jpg",
        "type": "Coupe",
        "location": "Chicago",
        "isNew": false
      },
      {
        "id": 4,
        "brand": "Audi",
        "model": "A4",
        "title": "Economical Excellence: Explore Our Honda Civic",
        "year": 2023,
        "mileage": 130,
        "maxSpeed": 290,
        "price": 24545,
        "oldPrice": 25545,
        "image": "audi-a4.jpg",
        "type": "Sedan"
      },
      {
        "id": 5,
        "brand": "Lamborghini",
        "model": "Aventador",
        "title": "maxSpeed Redefined: Lamborghini Aventador’s Supercar Legacy",
        "year": 2021,
        "mileage": 20,
        "maxSpeed": 320,
        "price": 200000,
        "oldPrice": 205000,
        "image": "lamborghini-aventador.jpg",
        "type": "Coupe"
      },
      {
        "id": 6,
        "brand": "Porsche",
        "model": "718 Boxster",
        "title": "Elegance Unleashed: The Porsche 718 Boxster",
        "year": 2022,
        "mileage": 60,
        "maxSpeed": 180,
        "price": 95000,
        "oldPrice": 98000,
        "image": "porsche-718.jpg",
        "type": "Convertible"
      },
      {
        "id": 7,
        "brand": "Jaguar",
        "model": "F-Pace",
        "title": "Luxury Meets Performance: Jaguar F-Pace Crossover",
        "year": 2020,
        "mileage": 95,
        "maxSpeed": 205,
        "price": 58000,
        "oldPrice": 60000,
        "image": "jaguar-fpace.jpg",
        "type": "SUV"
      },
      {
        "id": 8,
        "brand": "Volkswagen",
        "model": "Tiguan",
        "title": "Smooth Utility: Volkswagen Tiguan's Versatility",
        "year": 2021,
        "mileage": 110,
        "maxSpeed": 178,
        "price": 31000,
        "oldPrice": 32900,
        "image": "vw-tiguan.jpg",
        "type": "SUV"
      },
      {
        "id": 9,
        "brand": "Mazda",
        "model": "CX-5",
        "title": "Drive Boldly: Mazda CX-5's Modern Dynamics",
        "year": 2022,
        "mileage": 90,
        "maxSpeed": 220,
        "price": 27000,
        "oldPrice": 28000,
        "image": "mazda-cx5.jpg",
        "type": "SUV"
      },
      {
        "id": 10,
        "brand": "Honda",
        "model": "Civic",
        "title": "Reliable Innovation: Honda Civic Reimagined",
        "year": 2023,
        "mileage": 80,
        "maxSpeed": 310,
        "price": 23500,
        "oldPrice": 24000,
        "image": "honda-civic.jpg",
        "type": "Sedan"
      },
      {
        "id": 11,
        "brand": "Hyundai",
        "model": "Elantra",
        "title": "Sleek Design: Hyundai Elantra Elevates Expectations",
        "year": 2022,
        "mileage": 70,
        "maxSpeed": 150,
        "price": 21000,
        "oldPrice": 22000,
        "image": "hyundai-elantra.jpg",
        "type": "Sedan"
      },
      {
        "id": 12,
        "brand": "Ford",
        "model": "Mustang",
        "title": "Iconic Thrill: Ford Mustang Muscle Power",
        "year": 2021,
        "mileage": 55,
        "maxSpeed": 400,
        "price": 45000,
        "oldPrice": 46000,
        "image": "ford-mustang.jpg",
        "type": "Coupe"
      },
      {
        "id": 13,
        "brand": "Chevrolet",
        "model": "Corvette",
        "title": "Bold Innovation: Chevrolet Corvette's Super maxSpeed",
        "year": 2020,
        "mileage": 44,
        "maxSpeed": 265,
        "price": 70000,
        "oldPrice": 72000,
        "image": "chevrolet-corvette.jpg",
        "type": "Convertible"
      },
      {
        "id": 14,
        "brand": "Subaru",
        "model": "Forester",
        "title": "Built for Adventure: Subaru Forester’s Journey",
        "year": 2021,
        "mileage": 100,
        "maxSpeed": 198,
        "price": 28000,
        "oldPrice": 29000,
        "image": "subaru-forester.jpg",
        "type": "SUV"
      },
      {
        "id": 15,
        "brand": "Kia",
        "model": "Seltos",
        "title": "Smart Urban Drive: Kia Seltos Unleashed",
        "year": 2022,
        "mileage": 75,
        "maxSpeed": 175,
        "price": 25000,
        "oldPrice": 26000,
        "image": "kia-seltos.jpg",
        "type": "SUV"
      },
      {
        "id": 16,
        "brand": "Tesla",
        "model": "Model 3",
        "title": "Future on Wheels: Tesla Model 3 Electric Revolution",
        "year": 2023,
        "mileage": 15,
        "maxSpeed": 500,
        "price": 52000,
        "oldPrice": 54000,
        "image": "tesla-model3.jpg",
        "type": "Sedan"
      },
      {
        "id": 17,
        "brand": "Mercedes",
        "model": "C-Class",
        "title": "Executive Excellence: Mercedes-Benz C-Class Ride",
        "year": 2022,
        "mileage": 88,
        "maxSpeed": 210,
        "price": 60000,
        "oldPrice": 61000,
        "image": "mercedes-cclass.jpg",
        "type": "Sedan"
      },
      {
        "id": 18,
        "brand": "Jeep",
        "model": "Wrangler",
        "title": "Off-Road King: Jeep Wrangler Adventure Awaits",
        "year": 2021,
        "mileage": 150,
        "maxSpeed": 280,
        "price": 42000,
        "oldPrice": 43000,
        "image": "jeep-wrangler.jpg",
        "type": "SUV"
      },
      {
        "id": 19,
        "brand": "Renault",
        "model": "Duster",
        "title": "Tough Meets Affordable: Renault Duster Explored",
        "year": 2020,
        "mileage": 140,
        "maxSpeed": 135,
        "price": 19500,
        "oldPrice": 21000,
        "image": "renault-duster.jpg",
        "type": "SUV"
      },
      {
        "id": 20,
        "brand": "Skoda",
        "model": "Octavia",
        "title": "European Elegance: Skoda Octavia in Focus",
        "year": 2021,
        "mileage": 78,
        "maxSpeed": 155,
        "price": 26000,
        "oldPrice": 27000,
        "image": "skoda-octavia.jpg",
        "type": "Hatchback"
      }


]